version: '2'
services:
  ldap:
    image: ldap_ubuntu:latest
    ports:
      - 389:389
    volumes:
      - /etc/ldap
      - /var/lib/ldap
    labels:
      io.rancher.container.requested_ip: 10.42.88.87
    environment:
      - SLAPD_ROOT_PASSWORD=gftest@success
      - SLAPD_ROOT_DOMAIN=gftest.com
      - SLAPD_ORGANIZATION=gftest